// Code generated by ent, DO NOT EDIT.

package tlsfingerprintprofile

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the tlsfingerprintprofile type in the database.
	Label = "tls_fingerprint_profile"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldUserAgent holds the string denoting the user_agent field in the database.
	FieldUserAgent = "user_agent"
	// FieldEnableGrease holds the string denoting the enable_grease field in the database.
	FieldEnableGrease = "enable_grease"
	// FieldCipherSuites holds the string denoting the cipher_suites field in the database.
	FieldCipherSuites = "cipher_suites"
	// FieldCurves holds the string denoting the curves field in the database.
	FieldCurves = "curves"
	// FieldPointFormats holds the string denoting the point_formats field in the database.
	FieldPointFormats = "point_formats"
	// FieldSignatureAlgorithms holds the string denoting the signature_algorithms field in the database.
	FieldSignatureAlgorithms = "signature_algorithms"
	// FieldAlpnProtocols holds the string denoting the alpn_protocols field in the database.
	FieldAlpnProtocols = "alpn_protocols"
	// FieldSupportedVersions holds the string denoting the supported_versions field in the database.
	FieldSupportedVersions = "supported_versions"
	// FieldKeyShareGroups holds the string denoting the key_share_groups field in the database.
	FieldKeyShareGroups = "key_share_groups"
	// FieldPskModes holds the string denoting the psk_modes field in the database.
	FieldPskModes = "psk_modes"
	// FieldExtensions holds the string denoting the extensions field in the database.
	FieldExtensions = "extensions"
	// FieldCompressCertAlgos holds the string denoting the compress_cert_algos field in the database.
	FieldCompressCertAlgos = "compress_cert_algos"
	// FieldDelegatedCredentialsAlgorithms holds the string denoting the delegated_credentials_algorithms field in the database.
	FieldDelegatedCredentialsAlgorithms = "delegated_credentials_algorithms"
	// FieldApplicationSettingsProtocols holds the string denoting the application_settings_protocols field in the database.
	FieldApplicationSettingsProtocols = "application_settings_protocols"
	// Table holds the table name of the tlsfingerprintprofile in the database.
	Table = "tls_fingerprint_profiles"
)

// Columns holds all SQL columns for tlsfingerprintprofile fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldPlatform,
	FieldDescription,
	FieldUserAgent,
	FieldEnableGrease,
	FieldCipherSuites,
	FieldCurves,
	FieldPointFormats,
	FieldSignatureAlgorithms,
	FieldAlpnProtocols,
	FieldSupportedVersions,
	FieldKeyShareGroups,
	FieldPskModes,
	FieldExtensions,
	FieldCompressCertAlgos,
	FieldDelegatedCredentialsAlgorithms,
	FieldApplicationSettingsProtocols,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultPlatform holds the default value on creation for the "platform" field.
	DefaultPlatform string
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// DefaultUserAgent holds the default value on creation for the "user_agent" field.
	DefaultUserAgent string
	// UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	UserAgentValidator func(string) error
	// DefaultEnableGrease holds the default value on creation for the "enable_grease" field.
	DefaultEnableGrease bool
)

// OrderOption defines the ordering options for the TLSFingerprintProfile queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByUserAgent orders the results by the user_agent field.
func ByUserAgent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserAgent, opts...).ToFunc()
}

// ByEnableGrease orders the results by the enable_grease field.
func ByEnableGrease(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnableGrease, opts...).ToFunc()
}
